version: "3.8"

services:
  db:
    image: postgres:alpine3.16
    restart: always
    environment:
      TZ: "America/Recife"
      POSTGRES_USER: "root"
      POSTGRES_PASSWORD: "root"
      POSTGRES_DB: "igti-hexagonal"
    ports:
      - 5432:5432

  adminer:
    image: adminer
    ports:
      - 8081:8080